### ISSUE TITLE
what the difference between the other way to update the UI thread from a background thread

### ISSUE THREAD

**Issue by lindexi** [Microsoft/Windows-task-snippets#3]
I want to know what the difference between 

      await CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(
          CoreDispatcherPriority.Normal,()=>
          {
               //Up date
         });

and 

       await Window.Current.Dispatcher.RunAsync(CoreDispatcherPriority.High,
               () =>
               {
                   //Up date 
               });

**Comment by KarlErickson** [comment]
See [CoreDispatcherPriority](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.core.coredispatcherpriority.aspx) in the docs for info on this.

**Comment by oldnewthing** [comment]
Also, one dispatches to the main view, whereas the other dispatches to the current window.

**Comment by KarlErickson** [comment]
Thanks - I didn't see that part.

**Comment by lindexi** [comment]
Ths.If have no the  current window as run in app.xaml.cs when the app running ,both will say null ref.And if it run in http await methor,the second will find the current is null.
